#!/bin/bash

xrun -uvm +incdir+../src +incdir+../rtl +incdir+../example -access rwc ../example/tb_example.sv +UVM_TESTNAME=$1 -gui -coverage all -covoverwrite -input restore.tcl
#+UVM_OBJECTION_TRACE +UVM_VERBOSITY=UVM_DEBUG
